apiVersion: apps/v1
kind: Deployment                    # This cache deployment file so kind is Deployment
metadata:
  name: cache-deployment
  namespace: default                # We hve given default namespace so the pod will be created under the default namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache                  # Cache Pod will be created with the lable cashe
  spec:
    containers:
    - name: redis
      image: redis                  # Image and their port was mention it was expose on port 6379
      ports:
    - containerPort: 6379
