# We hae Use a lightweight Node.js base image to run the Node.js application
FROM node:alpine

# Set the working directory inside the container where we can copy the dependencies package files
WORKDIR /app

# Copy package files for installing dependencies
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the application code to the container
COPY . .

# Expose the port the app runs on
EXPOSE 3000

# Command to run the application
CMD ["npm", "start"]