apiVersion: v1
kind: Service                      # This service file so kind is service
metadata:
  name: my-app-service
  namespace: default
spec:
  selector:
    app: my-app-deployment         # It select the app with the lable my-app-deployment and assign the port
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
