apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: my-app-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: my-app-deployment
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        # Allow incoming traffic from all pods in the same namespace
        - podSelector: {}
        # Allow incoming traffic from a specific pod with label app=trusted
        - podSelector:
            matchLabels:
              app: trusted
  egress:
    - to:
        # Allow outgoing traffic to all pods in the same namespace
        - podSelector: {}
  # Default deny rules are implicit unless specified in ingress or egress